[package]
name = "echelon0"
version = "0.1.0"
authors = ["Ivan Velichko <iximiuz@gmail.com>"]

[dependencies]
getopts = "0.2"

[dependencies.monstrio]
version = "0.1"
features = ["glob"]
path = "../../crates.rs/monstrio"
