[package]
name = "echelon0"
version = "0.1.0"
authors = ["Ivan Velichko <iximiuz@gmail.com>"]

[dependencies]
chrono = "0.2"
env_logger = "0.3"
getopts = "0.2"
regex = "0.1"

[dependencies.monstrio]
version = "0.1"
features = ["glob"]
path = "../../crates.rs/monstrio"
